title: shbhsu's info
author: shbhsu
email: shbhsu@gmail.com
lang: zh-TW
description: SHBHSU
 
baseurl: "" # the subpath of your site, e.g. /blog


permalink: /:categories/:title/
sass:
  style: compressed

